import React, { useRef, useState } from "react";

const API = import.meta.env.VITE_API_BASE_URL || (window.location.port === "5173" ? "http://127.0.0.1:8000" : "");

export default function WebcamCapture({ onCapture, compact = false }) {
  const videoRef = useRef(null);
  const canvasRef = useRef(null);
  const [cameraStarted, setCameraStarted] = useState(false);
  const [processing, setProcessing] = useState(false);
  const [error, setError] = useState("");
  const [engine, setEngine] = useState("");

  const startCamera = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: true, audio: false });
      videoRef.current.srcObject = stream;
      setCameraStarted(true);
      setError("");
    } catch (err) {
      setError("Camera access failed. Please allow webcam permission.");
    }
  };

  const captureFace = async () => {
    const video = videoRef.current;
    const canvas = canvasRef.current;
    if (!video || !video.videoWidth) {
      setError("Camera is not ready yet.");
      return;
    }

    try {
      setProcessing(true);
      setError("");
      setEngine("");

      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      const context = canvas.getContext("2d");
      context.drawImage(video, 0, 0);
      const imageData = canvas.toDataURL("image/jpeg", 0.86);

      const response = await fetch(`${API}/biometric/extract`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ image_data: imageData }),
      });

      const data = await response.json();
      if (data.status !== "SUCCESS") {
        setError(data.message || "Biometric capture failed. Please retry.");
        return;
      }

      setEngine(data.signature_engine || "1Booking FaceID");
      onCapture({
        imageData,
        faceSignature: data.face_signature,
        signatureEngine: data.signature_engine,
        signatureHash: data.signature_hash,
      });
    } catch (err) {
      setError("Unable to reach biometric engine. Please make sure the backend is running on port 8000.");
    } finally {
      setProcessing(false);
    }
  };

  return (
    <div className={compact ? "webcam compact" : "webcam"}>
      <video ref={videoRef} autoPlay playsInline className="video" />
      <canvas ref={canvasRef} style={{ display: "none" }} />
      <div className="camera-actions">
        {!cameraStarted && <button className="secondary-btn" onClick={startCamera}>Start Camera</button>}
        {cameraStarted && <button className="secondary-btn dark" onClick={captureFace} disabled={processing}>{processing ? "Capturing..." : "Capture FaceID"}</button>}
      </div>
      {engine && <p className="success-note">Captured using {engine}</p>}
      {error && <p className="error-text">{error}</p>}
      <p className="tiny-note">1Booking FaceID mode: face signature is generated by the backend and only the biometric template is stored.</p>
    </div>
  );
}
